### ISSUE TITLE
ARM Arch support/request 

### ISSUE THREAD

**Issue by ech03** [ArminJo/ServoEasing#8]
Love love love the library, thanks for putting in the effort! Any chance of getting ARM arch support? Specifically I'm working on a project using Adafruit's Circuit Playground Express (https://www.adafruit.com/product/3333) which I believe utilizes the ARM7TDMI architecture.

**Comment by ArminJo** [comment]
Hi,
What happens when you compile the ServoEasing Examples for the Circuit Playground Express?
I get a lot of warnings, but not from my code :-) . Since I do not have this board I cannot check.

I added a new Simple Example to the repository which should run on any platform where the Arduino Servo library is available. 
Please tell me if it works for you.
